### PR TITLE
Updating literally everything

### PR DESCRIPTION
**Pull request by ryleu**
- FTC app version to 6.2.1
- Android SDK version to 30
- Gradle version to 7.0
- Java version to 1.8
- Roadrunner version to 0.5.3
- OpenCV version to 1.4.4
- Dashboard version to 0.4.1

### CODE REVIEW

**Review by wizardwatch — COMMENTED** [review]
I don't know if you care, but for reverted changes such as the .gitignore, you can squash(git rebase and merge) the commits to make the history and summary of changes a bit nicer. I wouldn't bother since this is all just formatting, but something to keep in mind for the future.

**Comment by ryleu** [comment]
> I don't know if you care, but for reverted changes such as the .gitignore, you can squash(git rebase and merge) the commits to make the history and summary of changes a bit nicer. I wouldn't bother since this is all just formatting, but something to keep in mind for the future.

I’ll need to learn how to do that. Good to know!

**Comment by wizardwatch** [comment]
This is building up to be pretty huge and people can't work on the main branch without this. @ryleu @SimonVerrill Do you see any reason not to merge?

**Review by SimonVerrill — APPROVED** [review]
it sure do work, only thing is that instead of RB, RF its now rightFront, rightRear but i changed that in config so we good

**Pull request merged**
